name: Safe Commit Bot

on:
  schedule:
    
cron: "0 6 * * *"   # щодня о 06:00 UTC
workflow_dispatch:       # можна запускати вручну

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      
name: Checkout repository (with creds)
      uses: actions/checkout@v4
      with:
        persist-credentials: true

      
name: Configure git user
      run: |
        git config --global user.name "Papatronik1"
        git config --global user.email "qwsxc192@gmail.com"

      
name: Generate random commits and push
      env:
        REPO: ${{ github.repository }}
        BRANCH: ${{ github.ref_name }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -e

          # кількість комітів (200..299)
          COUNT=$((200 + RANDOM % 100))
          echo "Буду робити $COUNT комітів"

          # переконаємось, що є файл для правок
          touch journal.md
          git add journal.md  true
          git commit -m "chore: ensure journal exists"  echo "no initial changes"

          for i in $(seq 1 $COUNT); do
            # додаємо рядок у journal.md
            echo "$(date -u) - commit $i - $RANDOM" >> journal.md
            git add journal.md
            git commit -m "Auto commit $i" || echo "no changes for commit $i"
          done

          # використати GITHUB_TOKEN для push (щоб уникнути помилки Permission denied)
          git remote set-url origin https://github.com/$%7BREPO%7D.git
          git push origin HEAD:${BRANCH}
